### ISSUE TITLE
Wrong response parsing in generated code

### ISSUE THREAD

**Issue by pahan35** [ahmader/node-zoho#27] opened 2018-02-07 17:01 UTC
I noticed that method **getRecordsById** in **crm-module.coffee** doesn't work correctly cause this code
```
if response.data?[@name]
  row = _.first(response.data?[@name])
  processed = @processRecord(_.first(row.row))
  response.data = processed
```

compiled like 
```
if ((_ref = response.data) != null ? _ref.Events : void 0) {
  row = _.first((_ref1 = response.data) != null ? _ref1.Events : void 0);
  processed = _this.processRecord(_.first(row.row));
  response.data = processed;
}
```
and not overrides in each child component to correct module name like **Contacts** etc
```
if ((_ref = response.data) != null ? _ref.Contacts : void 0) {
  row = _.first((_ref1 = response.data) != null ? _ref1.Contacts : void 0);
  processed = _this.processRecord(_.first(row.row));
  response.data = processed;
}
```

Have you any idea how to fix it?

UPD: actually I see error code in node package 0.0.26. When I build it manually it compiled correctly

**Comment by ahmader** [comment] 2018-02-07 19:53
Can you give me in steps how to reproduce the problem ?

It should compile the code while installing from npm exactly like if you build it manually.

Thank you

**Comment by ahmader** [comment] 2018-02-07 21:07
What is your node and npm versions ?

```
$ node --version && npm --version
```

**Comment by pahan35** [comment] 2018-02-07 23:57
I have node 8.9.3 and npm 5.5.1

Clean [bad compiled node-zoho](https://drive.google.com/file/d/1r0C32Jkg-c9lRQ9xWZIWmqRRkr8gBdX-/view?usp=sharing)
![image](https://user-images.githubusercontent.com/13823215/35948031-3a9ded30-0c73-11e8-82ed-1d2bd46ddcc8.png)

**Comment by ahmader** [comment] 2018-02-08 05:29
@pahan35 I have bumped the version to v0.0.28

Can you confirm if the problem is fixed now

**Comment by ahmader** [comment] 2018-02-08 19:05
Great,

I will close this issue, and hopefully to see you around

**Closed by ahmader** 2018-02-08 19:05 UTC
